name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo -----BEGIN OPENSSH PRIVATE KEY-----
  b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
  NhAAAAAwEAAQAAAYEA4XfpmGJpMuo4YOhScYrzML9j8+VHCwxsOCLkfN+GmKIzD3daWkLR
  3hj2bXv8Z1uieky16kTjEUY06BD1XlRKfiLj8Z1VzXRxs2lncB79ilcrgb1VjiDYzRB7m+
  zQyqY6kH4I8Culk04037sod/8y1Y585Hfqn4DdC/dal/bvMqMyMIeCwO/mtkRynZ1P3Mhy
  NbaqdtnEsDBwGJ9fmTe05Uf3qa4HhOJaOiHxZ7r9tT6SPiD57selhTMO+LPUQCMDUmYBr/
  KdmYycsxFr5/2mH+yTCfoh+SaRW4vTdOv1l2OTHyWqwMc6Al74OfJJfhUAt9+8MxQ+cIiK
  gQWcoCSb2Dniicx2tvUxbuIdBzL4KaUOWAxf1dOF20WGuuiNnyFN9ZEeTYEgYDbBUqzzb7
  I7p3Q0E1/AJS/NUFxIAHJgC0W0snNPp/SrUHA6JynpwJkVFvRxoKVm84DGzbAakp7e52u6
  qgtNKL6JYLOZMCUginwXwcF7KhEyL0CdvBB6UrIPAAAFmFE2545RNueOAAAAB3NzaC1yc2
  EAAAGBAOF36ZhiaTLqOGDoUnGK8zC/Y/PlRwsMbDgi5HzfhpiiMw93WlpC0d4Y9m17/Gdb
  onpMtepE4xFGNOgQ9V5USn4i4/GdVc10cbNpZ3Ae/YpXK4G9VY4g2M0Qe5vs0MqmOpB+CP
  ArpZNONN+7KHf/MtWOfOR36p+A3Qv3Wpf27zKjMjCHgsDv5rZEcp2dT9zIcjW2qnbZxLAw
  cBifX5k3tOVH96muB4TiWjoh8We6/bU+kj4g+e7HpYUzDviz1EAjA1JmAa/ynZmMnLMRa+
  f9ph/skwn6IfkmkVuL03Tr9Zdjkx8lqsDHOgJe+DnySX4VALffvDMUPnCIioEFnKAkm9g5
  4onMdrb1MW7iHQcy+CmlDlgMX9XThdtFhrrojZ8hTfWRHk2BIGA2wVKs82+yO6d0NBNfwC
  UvzVBcSAByYAtFtLJzT6f0q1BwOicp6cCZFRb0caClZvOAxs2wGpKe3udruqoLTSi+iWCz
  mTAlIIp8F8HBeyoRMi9AnbwQelKyDwAAAAMBAAEAAAGAJQeoLlZPV8TfAI93Zt1+xm1Qkb
  CAxABEz81vQFEHzo6pGyurg7KAvFzWMDISSLlkjHiH0hOBRYeFze1nFxh56ZB6ZmbEPkuX
  FvPDQMdeNbfOVe8OG5sqcDd6TagNvJKjgLKqbiOE/JX2Gh6nbVnU8/0EZxOIzayA4WO9Fc
  NBEsx5xD2lTGG6Pwor1tYM1UJ4e3jmM0Hdy2ARMQIP1d6vz45LzyrdYkY4sl57wuETpQ5D
  P3/z/HL+rMsvdMo4HFaDeKq/ZrYPPTVZbxyZfkqF+UGMgqfvBI/Yie/LSje4VNOg8c8Fq6
  O7e+5RDfFYzD6tLHqGvomfByJurFx3/fwznUJ19v9bc530z7CPwJsLDwjgQ/UQCQIcWihs
  528POmswYQHQ9fA+nD4cEMNiMT0oZDE2hI6jc5zy6JCiEfiaYD/6byhYCdcYmPjxWgwyVy
  gkB5D617+NBWEB9DAgG60qnCgmhL7mRNp8qFPqLPBrNLYJxGnbXB9vDos99bOj7o1JAAAA
  wQDVM9zxRx3Xd+gZi1ZXpBsOjX5sbdWRglxdsw7xLZKVHWd9HDqnTNEZ7xNDW65fthHaPN
  K5e3nLzcJJQzVrqT9hMDczK5coRJ8G7MqaGuYrguB4Ah87Tv++iLEpjEf5mA2H4U8DRS1A
  VRK6a1iY0d4wPdJ8tOr4REyaa+5gosBa6vbmNN357ykUS4NAOwyAVB1d0asQjMJkAMQeNI
  6wI2rMfWGkUOWKDKSDIwr+krnRv1iaFXE0JdagUELatslGTb0AAADBAOZG4iv3aZLNggyG
  KvY/KcpW15nMHoHUR8/USvcHL1y15mhou6GLmOt/YyngWyv+HnhW5hxN+OgD1qyhoUr1Fu
  uhhNb2NXWS4kH9BIZbpyB/fnVRyD4fGdhnQDjxLVB2xSgVIdqnZvakFj8V8ydf4dkZIhfD
  oJ8QFcjn0agAJCyVrODlKLrqccGYlKi6AosMVgPvDicAy9c3NJlScq0XFL8wI684GXnN/T
  8A/Tf732NEogTqvaGJ5YKlpkUhkHMfaQAAAMEA+qeF8VRb6vPjtdMOKvrnIU6TZJADAJ5J
  dK+enFZIX+bGF8ouq1LQ2Aph0FS/IX/GBlEwKGPKxADZGq5YoH5KLa209qA075Syk9XgEl
  JAqJW7iI48KjYVjLbXBevZVUe0VbP5gVeNhOhRvxwoSNAVD86bu91i7xXeql51c3wPcdfd
  UCzVtfb2Eapv5Y1Hd4PxHHB3eN9etmVLoezjcdyk/KFenS1X3WVQqfeGCDOGmYFYfwt5nk
  u9aU0Y9DOfY463AAAAHXJvb3RAMjMzMDgyMS1oczEwMTA0LnR3YzEubmV0AQIDBAU=
  -----END OPENSSH PRIVATE KEY----- > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      - run: cat "$HOME/.ssh/key"
      # Build
      - run: npm ci
      - run: npm run build
      # Deploy
      - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . root@82.97.240.163:/var/www/pepelsbey.dev/html/