name: 🚀 Deploy on push master

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Copy .env.prod to .env
        run: cp .env.prod .env

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: List output files
        run: find dist/ -print

      - name: 📂 Sync files
        run: |
          set -eu |
          mkdir "$HOME/.ssh" |
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCcsEmQFgmhSamNtorCPHLz7TaLojPRm5sdaUqXl+4tWbw0TU+PxFsRegc/AYgwvIQZIkf2umSqCclvl1Pep5L7bA8sQpH3PEjPvmJOpvU1c+EfOqaip6qUDNJ+dyumCJ9smkgYnj2AkCq/1AyjZU/8p9Ux1Vtx5APpljWxrDb8z+I9ojDIIHshaOjtkOXOoyej3UoSROYkBOhfAcl/pKDEIriOYmUFjQ1s6G4cAMkh9A9RN9s39/y7CNEJR09YNtvLhHRV73h6H7Tt3q/g+0jaGVVcZKIkmNQz9tuPE4Nig9zEalT8TlN/O9bNCdYJkPEOoF241TmMFcJzpKEBwBknGAzwAdCZahuZ2TA4GQ73zzlCPXxaCWcPrA7vA+fFUTUY2AK8LIe5BtV3iEtG+tiotvSdqRCm+VAz6C7kvSdk+pYakMyWL7wStWgQYPfT+e4t7hbIfuCoQGKT1+cMfLhJ6fUVp9LFKkSmdEY/6clCq3O8FZnwW/sRDItdlqq9hxE= eyese@DESKTOP-J3GOF64" > "$HOME/.ssh/key" |
          chmod 600 "$HOME/.ssh/key" |
          ssh root@82.97.240.163 |
          cd /home/ |
          touch test.txt |
